services:
  open-webui:
    # image: ghcr.io/open-webui/open-webui:main
    build:
      context: ./openwebui
      dockerfile: Dockerfile
    container_name: open-webui
    restart: always
    ports:
      - "3000:8080"
    volumes:
      - ~/.open-webui:/root/.open-webui
      - ~/.cache/huggingface:/root/.cache/huggingface 
      - ~/.cache/huggingface/hub:/root/.cache/huggingface/hub
      - open-webui:/app/backend/data
    networks:
      - internal-network
    environment:
      HF_HUB_OFFLINE: "1"
      OFFLINE_MODE: "true"
      DATA_DIR: "/root/.open-webui"
      HF_HOME: "/root/.cache/huggingface"
    extra_hosts:
      - "host.docker.internal:host-gateway"
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: always
    ports:
      - "11434:11434"
    healthcheck:
      test: ollama --version || exit 1
    command: serve
    volumes:
      - ollama:/root/.ollama
    networks:
      - internal-network
volumes:
  open-webui:
  ollama:

networks:
  internal-network:
    driver: bridge
    internal: true
